// Code generated by gen/genvals.go DO NOT EDIT.
package vals_test

import (
	"reflect"
	"testing"

	"github.com/mailund/cli/internal/vals"
)

func TestStringValue(t *testing.T) {
	var (
		x     string
		val = vals.AsValue(reflect.ValueOf(&x))
	)

	if val == nil {
		t.Fatal("val should not be nil")
	}

	if err := val.Set("foo"); err != nil {
		t.Error("error setting val to foo")
	}

	if val.String() != "foo" {
		t.Error("Unexpected string value for val")
	}
}

func TestVariadicStringValue(t *testing.T) {
	var (
		x    []string
		vv = vals.AsVariadicValue(reflect.ValueOf(&x))
	)

	if vv == nil {
		t.Fatal("vv should not be nil")
	}

	if err := vv.Set([]string{ "foo", "bar", "baz" }); err != nil {
		t.Error("vv.Set should not fail")
	}

	if !reflect.DeepEqual(x, []string{ "foo", "bar", "baz" }) {
		t.Error("x holds the wrong value")
	}
}

func TestBoolValue(t *testing.T) {
	var (
		x     bool
		val = vals.AsValue(reflect.ValueOf(&x))
	)

	if val == nil {
		t.Fatal("val should not be nil")
	}

	if err := val.Set("true"); err != nil {
		t.Error("error setting val to true")
	}

	if val.String() != "true" {
		t.Error("Unexpected string value for val")
	}

	if err := val.Set("foo"); err == nil {
		t.Error("val.Set() should fail this time")
	}
}

func TestVariadicBoolValue(t *testing.T) {
	var (
		x    []bool
		vv = vals.AsVariadicValue(reflect.ValueOf(&x))
	)

	if vv == nil {
		t.Fatal("vv should not be nil")
	}

	if err := vv.Set([]string{ "true", "false", "true" }); err != nil {
		t.Error("vv.Set should not fail")
	}

	if !reflect.DeepEqual(x, []bool{ true, false, true }) {
		t.Error("x holds the wrong value")
	}

	if err := vv.Set([]string{ "foo" }); err == nil {
		t.Error("vv.Set() should fail this time")
	}
}

func TestIntValue(t *testing.T) {
	var (
		x     int
		val = vals.AsValue(reflect.ValueOf(&x))
	)

	if val == nil {
		t.Fatal("val should not be nil")
	}

	if err := val.Set("42"); err != nil {
		t.Error("error setting val to 42")
	}

	if val.String() != "42" {
		t.Error("Unexpected string value for val")
	}

	if err := val.Set("foo"); err == nil {
		t.Error("val.Set() should fail this time")
	}
}

func TestVariadicIntValue(t *testing.T) {
	var (
		x    []int
		vv = vals.AsVariadicValue(reflect.ValueOf(&x))
	)

	if vv == nil {
		t.Fatal("vv should not be nil")
	}

	if err := vv.Set([]string{ "1", "2", "3" }); err != nil {
		t.Error("vv.Set should not fail")
	}

	if !reflect.DeepEqual(x, []int{ 1, 2, 3 }) {
		t.Error("x holds the wrong value")
	}

	if err := vv.Set([]string{ "foo" }); err == nil {
		t.Error("vv.Set() should fail this time")
	}
}

func TestFloat64Value(t *testing.T) {
	var (
		x     float64
		val = vals.AsValue(reflect.ValueOf(&x))
	)

	if val == nil {
		t.Fatal("val should not be nil")
	}

	if err := val.Set("3.14"); err != nil {
		t.Error("error setting val to 3.14")
	}

	if val.String() != "3.14" {
		t.Error("Unexpected string value for val")
	}

	if err := val.Set("foo"); err == nil {
		t.Error("val.Set() should fail this time")
	}
}

func TestVariadicFloat64Value(t *testing.T) {
	var (
		x    []float64
		vv = vals.AsVariadicValue(reflect.ValueOf(&x))
	)

	if vv == nil {
		t.Fatal("vv should not be nil")
	}

	if err := vv.Set([]string{ "0.1", "0.2", "0.3" }); err != nil {
		t.Error("vv.Set should not fail")
	}

	if !reflect.DeepEqual(x, []float64{ 0.1, 0.2, 0.3 }) {
		t.Error("x holds the wrong value")
	}

	if err := vv.Set([]string{ "foo" }); err == nil {
		t.Error("vv.Set() should fail this time")
	}
}
