// Code generated by genvals.go DO NOT EDIT.
package vals

import (
	"strconv"

	"github.com/mailund/cli/internal/params"
)

type StringValue string

func (val *StringValue) Set(x string) error {
	v, err := x, (error)(nil)
	if err != nil {
		err = params.ParseErrorf("argument \"%s\" cannot be parsed as string", x)
	} else {
		*val = StringValue(v)
	}

	return err
}

func (val *StringValue) String() string {
	return `"` + string(*val) + `"`
}

type BoolValue bool

func (val *BoolValue) Set(x string) error {
	v, err := strconv.ParseBool(x)
	if err != nil {
		err = params.ParseErrorf("argument \"%s\" cannot be parsed as bool", x)
	} else {
		*val = BoolValue(v)
	}

	return err
}

func (val *BoolValue) String() string {
	return strconv.FormatBool(bool(*val))
}

type IntValue int

func (val *IntValue) Set(x string) error {
	v, err := strconv.ParseInt(x, 0, strconv.IntSize)
	if err != nil {
		err = params.ParseErrorf("argument \"%s\" cannot be parsed as int", x)
	} else {
		*val = IntValue(v)
	}

	return err
}

func (val *IntValue) String() string {
	return strconv.Itoa(int(*val))
}

type Float64Value float64

func (val *Float64Value) Set(x string) error {
	v, err := strconv.ParseFloat(x, 64)
	if err != nil {
		err = params.ParseErrorf("argument \"%s\" cannot be parsed as float64", x)
	} else {
		*val = Float64Value(v)
	}

	return err
}

func (val *Float64Value) String() string {
	return strconv.FormatFloat(float64(*val), 'g', -1, 64)
}
